"""
Generate Markdown report + JSON state dump from final AnalysisState.
"""
import json
import os
from datetime import datetime
from utils.debug_logger import log_file_output, trace_event, summarize_state


def generate_report(state: dict, output_dir: str) -> str:
    """Write report.md and state_dump.json; return report markdown."""
    os.makedirs(output_dir, exist_ok=True)
    ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    val = state.get("validation_result") or {}
    man = state.get("manifest_result") or {}
    tnt = state.get("taint_result") or {}
    sem = state.get("semantic_result") or {}
    flo = state.get("flowdroid_result") or {}
    icc = state.get("icc_bridge_result") or {}
    sast = state.get("sast_prior_result") or {}

    exploitable = val.get("exploitable", False)
    verdict     = val.get("final_verdict", "N/A")

    # ── Cypher evidence table ─────────────────────────────────────────────
    cypher_rows = ""
    for item in val.get("cypher_queries", []):
        q   = item.get("query", "")
        ans = item.get("answer", "")
        if isinstance(ans, list):
            ans = "; ".join(str(a) for a in ans)
        cypher_rows += f"| {q} | {ans} |\n"

    # ── IntraPath list ────────────────────────────────────────────────────
    intra_list = ""
    for p in flo.get("intra_paths", []):
        intra_list += f"- **{p.get('id','')}**: `{p.get('source','')}` → `{p.get('sink','')}`\n"
    if not intra_list:
        intra_list = "_No IntraPath data (FlowDroid may have skipped or found no flows)._\n"

    # ── CrossPath list ────────────────────────────────────────────────────
    cross_list = ""
    for cp in icc.get("cross_paths", []):
        cross_list += (
            f"- **{cp.get('id','')}**: entry=`{cp.get('entry_component','')}` "
            f"vector=`{cp.get('attack_vector','')}` "
            f"confidence={cp.get('confidence', 0):.2f}\n"
        )
    if not cross_list:
        cross_list = "_No CrossPath data._\n"

    # ── SAST Tool Prior section ───────────────────────────────────────────
    sast_section = "_SAST prior fusion was not run._\n"
    if sast.get("status") == "success":
        stats = sast.get("stats", {})
        sast_section = (
            f"**Tools loaded:** {', '.join(sast.get('tools_loaded', []))}\n"
            f"**Findings fused:** {stats.get('total_fused', 0)} "
            f"(aligned={stats.get('aligned', 0)}, "
            f"candidate={stats.get('candidate', 0)}, "
            f"unmatched={stats.get('unmatched', 0)})\n"
            f"**HPG nodes enriched:** {stats.get('enriched_nodes', 0)}\n"
            f"**Hints written to graph:** {stats.get('hints_written', 0)} "
            f"(method={len(sast.get('method_hints', []))}, "
            f"component={len(sast.get('component_hints', []))})\n"
        )

    verdict_label = "EXPLOITABLE" if exploitable else "NOT EXPLOITABLE"
    cypher_table  = cypher_rows if cypher_rows else "| _No queries issued_ | -- |\n"
    evidence_block = (
        "```\n"
        "Manifest Agent  -->  root_path_protected=false (Neo4j)\n"
        "Taint Agent     -->  SuSi XML generated (Layer A input)\n"
        "FlowDroid       -->  IntraPath: query()->MatrixCursor.addRow() (Neo4j)\n"
        "ICC Bridge      -->  CrossPath: exported provider, no root permission (Neo4j)\n"
        "Validation Agent-->  Text2Cypher confirmed vulnerability (GraphRAG)\n"
        "```"
    )

    report = f"""# APK Security Analysis Report

**APK**: {state.get('apk_name', 'N/A')}
**Generated**: {ts}
**Final Verdict**: {verdict_label}

---

## 1. Manifest Analysis

{man.get('vulnerability', 'N/A')}

- **Root path protected**: {man.get('root_path_protected', 'unknown')}
- **Attack surface**: {man.get('attack_surface', 'N/A')}
- **Confidence**: {man.get('confidence', 0):.2f}

---

## 2. Taint Analysis — SuSi Source/Sink Inference

**Sources identified**: {tnt.get('sources', [])}
**Sinks identified**:  {tnt.get('sinks', [])}
**SuSi confidence**: {tnt.get('susi_confidence', 0):.2f}
**Needs semantic analysis**: {tnt.get('needs_semantic_analysis', False)}

---

## 3. Semantic Analysis (if triggered)

{sem.get('semantic_findings', '_Not triggered._')}

---

## 4. FlowDroid Layer A — Intra-Component Taint Paths

{intra_list}

---

## 5. ICC Bridge Layer B — Cross-Component Paths

{cross_list}

---

## 5.5 SAST Tool Prior Fusion

{sast_section}

---

## 6. GraphRAG Path Validation (Text2Cypher)

| Query | Neo4j Answer |
|-------|-------------|
{cypher_table}

### Verdict

{verdict}

**Exploitable**: {exploitable}

---

## 7. Evidence Chain

{evidence_block}

---

*Generated by LangGraph + Neo4j GraphRAG pipeline (Qwen3-235)*
"""

    report_path = os.path.join(output_dir, "report.md")
    with open(report_path, "w", encoding="utf-8") as f:
        f.write(report)
    log_file_output(report_path, label="report_markdown", agent="report_generator")

    dump_path = os.path.join(output_dir, "state_dump.json")
    # Make state JSON-serializable (drop non-serializable objects)
    safe_state = {}
    for k, v in state.items():
        if k == "app_smali":
            safe_state[k] = {kk: "<smali>" for kk in v}
        elif k == "app_java":
            safe_state[k] = {kk: "<java>" for kk in v}
        else:
            try:
                json.dumps(v)
                safe_state[k] = v
            except (TypeError, ValueError):
                safe_state[k] = str(v)
    with open(dump_path, "w", encoding="utf-8") as f:
        json.dump(safe_state, f, indent=2, ensure_ascii=False)
    log_file_output(dump_path, label="state_dump", agent="report_generator")
    trace_event(
        "report_generated",
        {"output_dir": output_dir, "state_summary": summarize_state(safe_state)},
        agent="report_generator",
    )

    print(f"[report_generator] Report written to {report_path}")
    print(f"[report_generator] State dump written to {dump_path}")
    return report
